version: '3.8'

services:
  my-tg-bot:
    build: .
    container_name: tg_bot
    restart: always
    environment:
      # 只需要这里填入 BotFather 给你的 Token 即可
      - BOT_TOKEN=8944669616:AAEwFUi-qAS041c1TGNhE-TF_QfOP_hydU4
